version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - migrate
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8083:8080"

  db:
    container_name: db
    image: postgres:15.1-bullseye
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  migrate:
    container_name: migrate
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: ["sh", "startup_migrate.sh"]
